import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { MoonIcon, SunIcon } from "@heroicons/react/outline";
import Input from "../components/Input";
import Button from "../components/Button";
import { useTheme } from "next-themes";

const Home: NextPage = () => {
  interface Character {
    name: string;
    height: number;
    mass: number;
    hair_color: string;
    birth_year: string;
    species: string[];
  }

  const [searchedValue, setSearchedValue] = useState<string>("");
  const [character, setCharacter] = useState<Character | null>(null);
  const [species, setSpecies] = useState<any>([]);
  const [films, setFilms] = useState<any>([]);
  const [starships, setStarships] = useState<any>([]);

  const { name, height, mass, hair_color, birth_year } = character || {};

  // controls dark/light mode, and favicon to match up with mode
  const { theme, setTheme } = useTheme();
  const [fav, setFav] = useState(
    theme === "dark" ? "/skywalker.ico" : "/vader.ico"
  );

  console.log(theme);

  return (
    <div className="h-screen w-screen bg-green-100 dark:bg-slate-800">
      <button
        className={`absolute top-1 right-1 p-2 
        `}
        onClick={() => {
          if (theme === "dark") {
            setTheme("light");
            setFav("/skywalker.ico");
          } else {
            setTheme("dark");
            setFav("/vader.ico");
          }
        }}
      >
        {theme === "dark" ? (
          <SunIcon className="w-6 h-6" />
        ) : (
          <MoonIcon className="w-6 h-6" />
        )}
      </button>

      <Head>
        <title>Star Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={fav} />
      </Head>

      <main className="max-w-[600px] min-h-screen flex flex-col mx-auto justify-center ">
        <section id="Character">
          <div className="bg-green-400 min-h-[400px] rounded-lg shadow-2xl p-4 ">
            <h1 className="text-center text-2xl">{name}</h1>
            <div className="flex p-4">
              <div className="basis-1/2">
                <h2 className="underline ">About Me</h2>
                <ul className="list-disc list-inside">
                  <li>Height:&nbsp;{height}cm</li>
                  <li>Weight:&nbsp;{mass}kg</li>
                  <li>Hair Color:&nbsp;{hair_color}</li>
                  <li>DOB:&nbsp;{birth_year}</li>
                  <li>
                    Species:
                    <ul className="list-disc ml-8 list-inside">
                      {species.map((species: any, index: number) => (
                        <li key={index}>{species.name}</li>
                      ))}
                    </ul>
                  </li>
                </ul>
              </div>
              <div className="basis-1/2 pl-8">
                <div className="">
                  <h2 className="underline">Films Appeared In</h2>
                  <ul className="list-disc list-inside">
                    {films.map((film: any, index: number) => (
                      <li key={index}>{film.title}</li>
                    ))}
                  </ul>
                </div>
                <div className="pt-5">
                  <h2 className="underline">Starships Flown</h2>
                  <ul className="list-disc list-inside">
                    {starships.map((starship: any, index: number) => (
                      <li key={index}>{starship.name}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        <form
          className="text-center mt-10"
          onSubmit={async (e) => {
            e.preventDefault();
            // Get the the searched character
            const character = await fetch(
              `https://swapi.dev/api/people/?search=${searchedValue}`
            )
              .then((response) => response.json())
              .then((response) => response.results[0]);

            // Get all films in parallel for which the searched character has starred
            const films = await Promise.all(
              character.films.map((film: string) =>
                fetch(film)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());

            // Get all starships in parallel for which searched character has flown
            const starships = await Promise.all(
              character.starships.map((starship: string) =>
                fetch(starship)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());

            // Get all species in parallel for which searched character is in
            const species = await Promise.all(
              character.species.map((species: string) =>
                fetch(species)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());
            setCharacter(character);
            setFilms(films);
            setStarships(starships);
            setSpecies(species);
          }}
        >
          <Input
            className="mr-2"
            placeholder="Enter the name of a character"
            value={searchedValue}
            onChange={(e) => {
              setSearchedValue(e.target.value);
            }}
          ></Input>
          <Button className="bg-green-400 text-black hover:bg-green-500">
            Lookup Character
          </Button>
        </form>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
