import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import {
  MoonIcon,
  SunIcon,
  PaperAirplaneIcon,
  VideoCameraIcon,
  UserIcon,
} from "@heroicons/react/outline";
import Input from "../components/Input";
import Button from "../components/Button";
import { useTheme } from "next-themes";

// To Do
// Consider using pseudo to reduce jsx icons for bullets, or use one icon in Header
// Consider setting up dark mode manually using local storage
// Finish dark/light mode colors
// Add validations:Need an error when there is no match, and return when no data.

const Home: NextPage = () => {
  interface Character {
    name: string;
    height: number;
    mass: number;
    hair_color: string;
    birth_year: string;
    species: string[];
  }

  const [searchedValue, setSearchedValue] = useState<string>("");
  const [character, setCharacter] = useState<Character | null>(null);
  const [species, setSpecies] = useState<any>([]);
  const [films, setFilms] = useState<any>([]);
  const [starships, setStarships] = useState<any>([]);

  const { name, height, mass, hair_color, birth_year } = character || {};

  // controls dark/light mode, and favicon to match up with mode
  const { theme, setTheme } = useTheme();
  const [fav, setFav] = useState(
    theme === "dark" ? "/skywalker.ico" : "/vader.ico"
  );

  console.log(theme);

  return (
    <div className="h-screen w-screen">
      <button
        className={`absolute top-1 right-1 p-2 ${
          theme === "dark" ? "hover:text-yellow-300" : "hover:text-indigo-500"
        }`}
        onClick={() => {
          if (theme === "dark") {
            setTheme("light");
            setFav("/skywalker.ico");
          } else {
            setTheme("dark");
            setFav("/vader.ico");
          }
        }}
      >
        {theme === "dark" ? (
          <SunIcon className="w-6 h-6" />
        ) : (
          <MoonIcon className="w-6 h-6" />
        )}
      </button>

      <Head>
        <title>Star Stars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={fav} />
      </Head>

      <main className="max-w-[600px] min-h-screen flex flex-col mx-auto justify-center ">
        <section id="Character">
          <div className="bg-green-300 rounded-lg shadow-xl p-4 dark:bg-gray-800 dark:border-2 dark: border-red-900 ">
            <h1 className="text-center h-10 font-extrabold text-3xl">{name}</h1>
            <div className="flex min-h-[350px] p-8">
              <div className="basis-1/2">
                <h2 className="underline ">About Me</h2>
                <ul className="">
                  <li className="flex items-center">
                    <UserIcon className="h-3 w-3" />
                    &nbsp;Height:&nbsp;{height}cm
                  </li>
                  <li className="flex items-center">
                    <UserIcon className="h-3 w-3" />
                    &nbsp;Weight:&nbsp;{mass}kg
                  </li>
                  <li className="flex items-center">
                    <UserIcon className="h-3 w-3" />
                    &nbsp;Hair Color:&nbsp;{hair_color}
                  </li>
                  <li className="flex items-center">
                    <UserIcon className="h-3 w-3" />
                    &nbsp;Born:&nbsp;{birth_year}
                  </li>

                  <li className="flex items-center">
                    <UserIcon className="h-3 w-3 flex" />
                    &nbsp;Species:&nbsp;
                  </li>
                  <ul className="block list-disc ml-8">
                    {species.map((species: any) => (
                      <li>{species.name}</li>
                    ))}
                  </ul>
                </ul>
              </div>
              <div className=" basis-1/2 flex flex-col pl-10 h-unset ">
                <div className=" basis-1/2">
                  <h2 className="underline">Appeared In</h2>
                  <ul className="">
                    {films.map((film: any, index: number) => (
                      <li key={index} className="flex items-center">
                        <VideoCameraIcon className=" animate-pulse h-3 w-3" />
                        &nbsp; {film.title}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="basis-1/2">
                  <h2 className="underline">Starships Flown</h2>
                  <ul className="">
                    {starships.map((starship: any, index: number) => (
                      <>
                        <li key={index} className="flex items-center">
                          <PaperAirplaneIcon className=" animate-spin h-3 w-3" />
                          &nbsp; {starship.name}
                        </li>
                      </>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        <form
          className="text-center mt-10"
          onSubmit={async (e) => {
            e.preventDefault();
            // Get the the searched character
            const character = await fetch(
              `https://swapi.dev/api/people/?search=${searchedValue}`
            )
              .then((response) => response.json())
              .then((response) => response.results[0]);

            // Get all films in parallel for which the searched character has starred
            const films = await Promise.all(
              character.films.map((film: string) =>
                fetch(film)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());

            // Get all starships in parallel for which searched character has flown
            const starships = await Promise.all(
              character.starships.map((starship: string) =>
                fetch(starship)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());

            // Get all species in parallel for which searched character is in
            const species = await Promise.all(
              character.species.map((species: string) =>
                fetch(species)
                  .then((response) => response.json())
                  .then((response) => response)
              )
            ).then((data: any) => data.flat());
            setCharacter(character);
            setFilms(films);
            setStarships(starships);
            setSpecies(species);
          }}
        >
          <Input
            className="mr-2"
            placeholder="Enter the name of a character..."
            value={searchedValue}
            onChange={(e) => {
              setSearchedValue(e.target.value);
            }}
          ></Input>
          <Button>Lookup Character</Button>
        </form>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
